[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies.tokio]
version = "1.24.1"
features = ["full"]

[dependencies]
database = {path = "../database"}
crossbeam-channel = "0.5.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"